version: '3.1'
services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=companyInfo
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - postgresqldb
#    ports:
#      - 9010:9010