version: '3.1'
services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=companyInfo
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgresqldb
    ports:
      - 8080:8080




#version: '3.1'
#services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD : pass
#      POSTGRES_DB : companyInfoDb
#      SPRING_DATASOURCE_URL : jdbc:postgresql://db:5432/companyInfoDb
#    ports:
#      - 5432:5432
#    expose:
#      - 5432
#
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8080:8080