version: '3.1'
services:
  authDb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=productInfoAuthUser
#  - "5432:5432"